apiVersion: v1
kind: Pod
metadata:
  name: final-gpu-test
  labels:
    test: production-ready
spec:
  restartPolicy: Never
  containers:
  - name: pytorch
    image: ghcr.io/ahmabboud/gpu_cluster_testing:latest
    imagePullPolicy: Always
    args:
    - "--model"
    - "resnet18"
    - "--batch-size"
    - "128"
    - "--active-iterations"
    - "10"
    - "--data-mode"
    - "synthetic"
    resources:
      limits:
        nvidia.com/gpu: 2
        memory: "32Gi"
      requests:
        nvidia.com/gpu: 2
        memory: "16Gi"
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
    securityContext:
      privileged: true
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "8Gi"
