apiVersion: v1
kind: Pod
metadata:
  name: gpu-cluster-test-single-gpu
  namespace: default
  labels:
    app: gpu-cluster-test
    mode: single-gpu
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: ghcr.io/ahmabboud/gpu_cluster_testing:latest
    imagePullPolicy: Always
    args:
      - "--model"
      - "resnet18"
      - "--batch-size"
      - "128"
      - "--warmup-iterations"
      - "10"
      - "--active-iterations"
      - "20"
      - "--data-mode"
      - "synthetic"
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 4Gi
